### ISSUE TITLE
1.business_day.before(date) not working

### ISSUE THREAD

**Issue by valk** [bokmann/business_time#101]
Please consider the following:

> date = '12-Jan-2015'.to_date
=> Mon, 12 Jan 2015
> 1.business_day.before(date)
=> Fri, 09 Jan 2015 00:00:00 UTC +00:00

> date = '11-Jan-2015'.to_date
=> Sun, 11 Jan 2015
> 1.business_day.before(date)
=> Thu, 08 Jan 2015 00:00:00 UTC +00:00

Same result if I set:

BusinessTime::Config.work_week = %w[mon tue wed thu fri]

It looks like a bug or am I missing any relevant setting?

Thanks.

**Comment by mifix** [comment]
Looking at the test, it seems this is intended behaviour:
> it "move to thursday if we subtract one business day during a weekend" do


I just stumbled upon this issue myself, because after an update to the latest version of this gem my tests blew up. 

To be honest, I do not understand the logic behind this change.

**Comment by mifix** [comment]
I think I just found the explanation in issue #45.  Looks like this was intended this way from the beginning.
