### ISSUE TITLE
Holiday patterns

### ISSUE THREAD

**Issue by natedavisolds** [bokmann/business_time#105]
Many of our holidays are repeated year to year.  These generally falling to an easy pattern.  First Monday in September or December 25th.

I've looked but can't find if patterns are currently acceptable in business_time.yml file.  If not, do you think it would be a worthwhile change? If so, I can work on and submit a pull request.

**Comment by bokmann** [comment]
I'd rather rely on the holidays gem to figure out that kind of stuff, and have this configuration just be a dumb list.  Any time I've tried to deal with repeating things on calendars the logic becomes twisty and filled with exceptions and locale variants.
