### ISSUE TITLE
multiple configuration for each record

### ISSUE THREAD

**Issue by asnad** [bokmann/business_time#106]
[business_time](https://github.com/bokmann/business_time) is great gem but I wanted to know can I use it for multiple business hours for multiple records for example I have multiple records of restaurants which have different business timings like this

    [
      Mon: {
        morning: {
          from: 9:00 am, to: 12:00 pm
        },
        noon:{
          from: 2:00 am, to: 5:00 pm
        },
        night{
          from: 7:00pm to: 11:pm
        }
      },
      Tue: {
        morning: {
          from: 10:00 am, to: 12:00 pm
        },
        noon:{
          from: 1:00 am, to: 5:00 pm
        },
        night: {
          from: 7:00pm to: 11:pm
        }
      },
      Wed: {
        morning: {
          from: 9:30 am, to: 12:00 pm
        },
        noon:{
          from: 1:30 am, to: 5:00 pm
        },
        night:{
          from: 7:00pm to: 11:pm
        }
      },
      Thu:{
        morning: {
          from: 9:00 am, to: 01:00 pm
        },
        noon:{
          from: 1:00 am, to: 5:00 pm
        },
        night:
        {
          from: 7:00pm to: 11:pm
        }
      },
      Fri:{
        morning: {
          from: 9:00 am, to: 01:00 pm
        },
        noon:{
          from: 1:00 am, to: 5:00 pm
        },
        night:{
          from: 7:00pm to: 11:pm
        }
      }
      Sat: off
      Sun: off
    ]
Can I use this gem for to implement this? if yes then How?

**Comment by craiglittle** [comment]
Hey, @asnad! I don't think `business_time` currently supports this feature; however, we just released a similar gem called [`biz`](https://github.com/zendesk/biz) that should work quite well for your use case.

Check out the documentation, and if you continue to have any questions, feel free to shoot me an email or open an issue.

**Comment by asnad** [comment]
Thanks for your response I will check biz.
