### ISSUE TITLE
No method error first_business day

### ISSUE THREAD

**Issue by btrscott** [bokmann/business_time#110]
Time.first_business_day(time_off_request.date_requested)

undefined method `first_business_day' for Time:Class  (Also did not work for date class).

time_off_request.num_days.business_days.after(time_off_request.date_requested) does work so library is generally working

Even example on readme page not working
 = Time.first_business_day(Time.parse("Sat Aug 9, 18:00:00, 2014"))

Method still available?

Ruby 2.2.1  Rails 4.2

**Comment by btrscott** [comment]
Seems like business_dates_until not working either.  Essentially anything that tries to extend Date or Time class are failing for me.

**Comment by btrscott** [comment]
I put all 3 of the class extensions into my business_time.rb initializer file and now they work.  

Not enough of a gem maker to fix why the gem is not including the extensions for 4.2; I'll see if I can find time to study up if someone doesn't patch this beforehand.

**Comment by bokmann** [comment]
It seems there are issues against a new version of ActiveSupport.  I'll investigate.  I personally haven't used it against that version yet, but such use will be needed soon.

**Comment by bokmann** [comment]
Closing this because I believe it is a symptom of issue #113
