### ISSUE TITLE
Calculates next business day wrong for a Sunday

### ISSUE THREAD

**Issue by btrscott** [bokmann/business_time#111]
Default configs.  Saturday says 1 business day after is Monday.  Friday says one business day after is Friday (itself).  Thursday says 1 business day after is Thursday (itself).  Sunday says 1 business day after is Tuesday.  Would expect it to be Monday; same answer for Saturday since weekend is non-business day.

2.1.2 :014 > d = Date.parse("2015-03-28")
 => Sat, 28 Mar 2015
2.1.2 :015 > 1.business_days.after(d)
 => Mon, 30 Mar 2015 20:00:00 EDT -04:00
2.1.2 :016 > d = Date.parse("2015-03-29")
 => Sun, 29 Mar 2015
2.1.2 :017 > 1.business_days.after(d)
 => Tue, 31 Mar 2015 20:00:00 EDT -04:00
2.1.2 :018 > d = Date.parse("2015-03-27")
 => Fri, 27 Mar 2015
2.1.2 :019 > 1.business_days.after(d)
 => Fri, 27 Mar 2015 20:00:00 EDT -04:00
2.1.2 :020 > d = Date.parse("2015-03-26")
 => Thu, 26 Mar 2015
2.1.2 :021 > 1.business_days.after(d)
 => Thu, 26 Mar 2015 20:00:00 EDT -04:00
2.1.2 :022 >

**Comment by vpuzzella** [comment]
Weird stuff for me too after updating to Ruby 2.2.1 from 2.1.5:
```
2.2.1 :028 > friday = '2015-04-10'.to_time
 => 2015-04-10 00:00:00 UTC 
2.2.1 :029 > saturday = '2015-04-11'.to_time
 => 2015-04-11 00:00:00 UTC 
2.2.1 :030 > 1.business_day.after(friday)
 => Mon, 13 Apr 2015 00:00:00 UTC +00:00 
2.2.1 :031 > 1.business_day.after(saturday)
 => Tue, 14 Apr 2015 00:00:00 UTC +00:00 
2.2.1 :032 > 
```

**Comment by bokmann** [comment]
Closing this because I believe it is a symptom of issue #113
