### ISSUE TITLE
Is this library still being supported?

### ISSUE THREAD

**Issue by btrscott** [bokmann/business_time#112]
Open issues go back over a year.  Last master was release about 10 months ago.  If this is dead, that should be announced in the readme and people can either fix themselves or move on.

Seems dead to me.

**Comment by craiglittle** [comment]
@btrscott, with all due respect to @bokmann, if you're having ongoing issues with `business_time`, you might want to check out some of the alternatives. I maintain a gem called [`biz`](https://github.com/zendesk/biz) that, looking at the issues you've opened, should be a good fit for your use cases. [`working_hours`](https://github.com/Intrepidd/working_hours) is another good one.

If you decide to use `biz`, I'm more than happy to help with any issues you might run into.

**Comment by bokmann** [comment]
This project is not dead, it is just 'suitable for original purpose'.  It is in use on the several projects it was originally created for, and countless ones beyond that.  There are several open issue and several open pull requests, but I haven't had time to take on and deal with them; they aren't pain points I'm feeling, and they take back burner to a million other things.
