### ISSUE TITLE
Something wrong with after method

### ISSUE THREAD

**Issue by kivanio** [bokmann/business_time#114]
After last update i've seen some weird result from 'after' method:

Sample:
<pre>
4.2.1@2.2.2 (main)> d = Date.parse('2015-05-29')
=> Fri, 29 May 2015
4.2.1@2.2.2 (main)> 0.business_days.after(d)
=> Fri, 29 May 2015
4.2.1@2.2.2 (main)> 1.business_days.after(d)
=> Mon, 01 Jun 2015
4.2.1@2.2.2 (main)> d = Date.parse('2015-05-30')
=> Sat, 30 May 2015
4.2.1@2.2.2 (main)> 1.business_days.after(d)
=> Tue, 02 Jun 2015
4.2.1@2.2.2 (main)> 0.business_days.after(d)
=> Mon, 01 Jun 2015
</pre>

Both results should not be Mon, 01 Jun 2015?

I want to get first business day after a date

**Comment by turbochef** [comment]
I'm having a similar issue with days_from_now

(current date is august 3 and workweek is 9-6 m-f)
2.1.5 :002 > 0.business_day.from_now
 => Thu, 06 Aug 2015 10:14:48 CDT -05:00
2.1.5 :003 > 1.business_day.from_now
 => Mon, 10 Aug 2015 10:15:19 CDT -05:00

**Comment by turbochef** [comment]
My issue came up after I started messing with my activerecord timezone.  Fixed afterwards by running the generator again.  Works as expected, great gem.
