### ISSUE TITLE
end_of_workday shouldn't be taken literal

### ISSUE THREAD

**Issue by faelsoto** [bokmann/business_time#117]
First of all, thanks for such a great gem!

I'm not really sure if this is an issue since it's something about the way we communicate. When we set up an option to set the business hours for a webapp and the user sets the opening and closing hours (let's say 10:00am and 5:30pm), he would expect his business to be open at 10:00am and stay open until the minute of 5:30pm runs out, so at 5:30:59 is open, but it's closed at 5:31:00.

However, that's not happening, if the closing hour is set to 5:30, the last second it will stay open is 5:29:59.

I know the configuration can be set to include seconds, however, how many people will use it? I think it should be a default until otherwise is stated.

What I ended up doing was monkeypatching the method and adding 1 minute:

```
module BusinessTime
  module TimeExtensions
    module ClassMethods
      def end_of_workday(day)
        end_of_workday = Time.parse(BusinessTime::Config.end_of_workday(day)) + 1.minute
        change_business_time(day,end_of_workday.hour,end_of_workday.min,end_of_workday.sec)
      end
    end
  end
end
```

Maybe the way to go would be via a config setting?

**Comment by bokmann** [comment]
Interesting, but this gem was originally written for a school system that had to be legally compliant under some court rulings having to do with time-to-completion for student issues, and the time needed to be taken literally as-is.  Changing business logic like that after this gem has existed for years would affect people in unknown and unplanned ways.
