### ISSUE TITLE
Is it possible to create multiple objects with different worktimes?

### ISSUE THREAD

**Issue by giovannibonetti** [bokmann/business_time#118]
Hi! First of all, great project!
I just stumbled upon it, and I was wondering if it is possible to create multiple instances of the base class with different business hours.
Something like this:

```ruby
bt = BusinessTime.new(work_hours: {mon: ["9:00","17:00"], tue: ["10:00","15:00"]})
friday = Date.parse("December 24, 2010")
monday = Date.parse("December 27, 2010")
bt.business_days_until(friday, monday)
```

My use case is that in my startup we manage beauty salons which have many different opening times, with professionals that may have different working hours.

**Comment by craiglittle** [comment]
Hey, @giovannibonetti!

@bokmann has mentioned in other issues that he's not particularly impelled to add this feature as it's not useful for his purposes. However, it *is* a feature we needed at our company, so we added it to our own `business_time`-like gem called [`biz`](https://github.com/zendesk/biz). Check out the `README` for details on how to configure; it's very similar to `business_time`. Feel free to ping me over there if you run into any issues!

**Comment by giovannibonetti** [comment]
Thanks, @craiglittle!
