### ISSUE TITLE
Consider changing the gem name

### ISSUE THREAD

**Issue by adelevie** [bokmann/business_time#124]
Hi @bokmann,

I don't really expect this to sway you, but oh well, I'll try.

I just started using this gem at work. I found out what the gem name references, and it's not super professional and could be reasonably alienating (making people not very comfortable at work).

I know it's technically super annoying to change the gem name (maybe publish to two gem names on rubygems? another hassle, I know).

I say all this as a one-time very tired/thankless OSS dev/maintainer. You made this gem, I didn't, and I get that. If anything, please just give this idea a couple minutes of thought.

-Alan

**Comment by bokmann** [comment]
This gem existed for more than a year before I even knew the pop culture reference you're making existed.  This gem was not named after that song, it was named solely for the purpose it served in the business logic from which it was extracted.  I was kinda annoyed when I first found out about it; I hate making references that might not fit in professional contexts.

As far as 'not being super professional', Really, any name can be co-opted by a pop culture reference (just ask the poor guy in 'Office Space' named 'Michael Bolton'!), and I don't want to change the name to avoid one that I wasn't referencing in the first place.

**Comment by adelevie** [comment]
Hey @bokmann, 

I really appreciate the response! 

For whatever reason, I am much happier knowing the (non-)origins to the gem name.

-Alan
