### ISSUE TITLE
What changed?

### ISSUE THREAD

**Issue by bmulholland** [bokmann/business_time#131]
It looks like business_time 0.7.5 has come out with changes spanning a year. I have upgraded - it's just a minor version - and that has broken my tests. Perhaps this change should have been labeled as larger than just a point release?

So what's changed? Where can I start my investigation? I looked at the commit log but there's so many it's hard to dig out what could have affected me.

**Comment by amilligan** [comment]
Yes please.  A changelog would be lovely.

**Comment by muzfuz** [comment]
It seems to be one of the biggest changes is around handling of business days now being defaulted to 9am to 5pm, instead of 12am to 11:50pm.  

Make sure you generate your yaml config file (using generator in the README), and change the settings there.  This helped fix this issues at my end.

**Comment by bokmann** [comment]
The break you mention in the other ticket I cannot reproduce and have requested more information on.  The changelog wasnot kept, but will be recreated from the pull requests that were accepted during that period.

I apologize, it won't happen again.
