### ISSUE TITLE
Lunch hours

### ISSUE THREAD

**Issue by vraravam** [bokmann/business_time#137]
I have a requirement to handle business hours as 8 am to 5 pm - but with a 1 hour lunch time in between that is not considered business hours. Is there any way by which this is already implemented in the codebase? My main usecase is to find out how many business hours exist between 2 given Time instances - but that needs to deduct the 1 hour lunch for each working day (and also needs to not deduct if the end time is by 12:00 noon).

**Comment by craiglittle** [comment]
@vraravam This is a feature of [`biz`](https://github.com/zendesk/biz), which I maintain, and [`working_hours`](https://github.com/Intrepidd/working_hours). You might want to check those gems out!

**Comment by vraravam** [comment]
@craiglittle - tx for pointing out `biz` and `working_hours` - I will review them and possibly move to one of them!
