### ISSUE TITLE
question about from_now

### ISSUE THREAD

**Issue by loicginoux** [bokmann/business_time#140]
I have a behaviour that seems weird:

```
2.3.1 :010 > Date.today
Thu, 29 Sep 2016

2.3.1 :011 > 1.business_days.after(Date.today)
Fri, 30 Sep 2016

2.3.1 :012 > 1.business_days.from_now
Mon, 03 Oct 2016 09:00:00 CEST +02:00

2.3.1 :013 > BusinessTime::Config.work_week
[
    [0] "mon",
    [1] "tue",
    [2] "wed",
    [3] "thu",
    [4] "fri"
]
```

I would have expected `1.business_days.from_now.to_date == 1.business_days.after(Date.today)`
is that the expected behaviour ?

**Comment by the-bass** [comment]
I'd say this behavior is totally ok _if_, by the time you did `> 1.business_days.from_now`, the working day was already over (by default, a working day ends at 5 pm, if I remember correctly). Note, that `1.business_days.from_now` uses the current _time_ as the reference, while `1.business_days.after(Date.today)` uses the current _date_.

**Comment by loicginoux** [comment]
If I see the time I created this issue (~7pm) it looks like it falls into this case, I didn't think about this work hours... So I'll just close the ticket. Thanks.
