### ISSUE TITLE
Incorrect calculation of (# of days).business_days.before(DATE)

### ISSUE THREAD

**Issue by AAlvarez90** [bokmann/business_time#141]
For example, if DATE is a Sunday, then:

``` ruby
1.business_days.before(DATE_SUNDAY) = Thursday.
```

Which is wrong, it should take me to the previous Friday. So it's going 1 extra business days back in time.

PS:
This offset is happening only when DATE is a weekend, if it's a week day it works fine.

**Comment by xlts** [comment]
@AAlvarez90 it's a known behavior and is being discussed in https://github.com/bokmann/business_time/pull/116 (this applies to your other issue as well); however it doesn't seem to be changed anytime soon.

**Comment by bokmann** [comment]
Closing because tthis is a dup of #116.  I believe the discussion happening in #126 applies here as well.
