### ISSUE TITLE
Incorrect calculation of (# of days).business_days.after(DATE)

### ISSUE THREAD

**Issue by AAlvarez90** [bokmann/business_time#142]
Assuming that DATE is a SUNDAY.
Then:

``` ruby
1.business_days.after(DATE) should equal a MONDAY. Right now it gives back a Tuesday which is wrong.
```

PS:
This offset is happening only when DATE is a weekend, if it's a week day it works fine.

**Comment by markrainer** [comment]
The way business time was designed is that 1 business day will go by. So Tuesday AM is the correct value. This ticket can be closed.
