### ISSUE TITLE
midnight to midnight

### ISSUE THREAD

**Issue by inopinatus** [bokmann/business_time#146]
How do I configure business_time to accept that we never close? That is, there is no time-of-day that should be rolled forward to the next business day.

Here's what I want

```` ruby
BusinessTime::Config.end_of_workday = "00:00" # we never close
#...
ts = Time.parse('2016-01-11 23:59:59.999')
1.business_day.after(ts).strftime("%Y-%m-%d %H:%M:%S.%L") #=> "2016-01-12 23:59:59.999"
````

Right now I get `"2016-01-13 23:59:59.999"` which is not right.
You might ask "why are you using business_time?" and the answer is "there is no business_date gem".
I have also tried `BusinessTime::Config.end_of_workday = "24:00"` without success.

**Comment by inopinatus** [comment]
my workaround is to extract the date part, use that with business_time and then add the time back in e.g. (with Rails extensions), but I don't know if it is wisest, there seems to be slight loss of precision.

````ruby
ts = Time.parse('2016-01-11 23:59:59.999')
date = ts.date
seconds = ts.seconds_since_midnight
1.business_day.after(date).to_time.advance(seconds: seconds).strftime("%Y-%m-%d %H:%M:%S.%L") #=> "2016-01-12 23:59:59.998"
````

**Comment by inopinatus** [comment]
Ok I have a workaround, extract the date, roll that forward, then put it back in.

````ruby
ts = Time.parse('2016-01-11 23:59:59.999')
new_date = 1.business_day.after(ts.to_date)
ts.change(year: new_date.year, month: new_date.month, day: new_date.day).strftime("%Y-%m-%d %H:%M:%S.%L") #=> "2016-01-12 23:59:59.999"
````

Feels like a kludge, but does seem to bypass the workday times completely.

**Comment by craiglittle** [comment]
You might want to check out a similar gem I maintain, [`biz`](https://github.com/zendesk/biz). It can handle all-day hours out of the box.

**Comment by bokmann** [comment]
Interesting case, but I wuld suggest either:
1) living with the workaround you have
2) investigating biz
3) contributing a patch back.  I'd gladly accept this concept with docs and tests.
4) extracting what you need from my code and creating a busines_date gem
