### ISSUE TITLE
warning: constant ::Fixnum is deprecated with Ruby 2.4.0

### ISSUE THREAD

**Issue by srpouyet** [bokmann/business_time#147]
`Fixnum` and `Bignum` were [unified into `Integer`](https://bugs.ruby-lang.org/issues/12005) in Ruby 2.4.0. When using `business_time` with Ruby 2.4.0, the following warning is displayed:
```
/Users/sebastiaan/.gem/ruby/2.4.0/gems/business_time-0.7.4/lib/business_time/core_ext/fixnum.rb:6: warning: constant ::Fixnum is deprecated
```

Thanks for `business_time`!

Cheers,
Sebastiaan

**Comment by tom-lord** [comment]
I have submitted a pull request to resolve this issue: https://github.com/bokmann/business_time/pull/148

**Comment by bokmann** [comment]
The new release addresses this.  Thanks!
