### ISSUE TITLE
Possible regression in 0.9.2 re: 0.business_days.before(date)

### ISSUE THREAD

**Issue by jaredbeck** [bokmann/business_time#164]
# 0.9.1

```
BusinessTime::VERSION #=> "0.9.1"
0.business_days.before(::Date.new(2016, 1, 30)) 
#=> Fri, 29 Jan 2016
```

# 0.9.2

```
BusinessTime::VERSION #=> "0.9.2"
0.business_days.before(::Date.new(2016, 1, 30)) 
# => Mon, 01 Feb 2016
```

I prefer the behavior in 0.9.1. My thinking: The number `0` is ambiguous, so the direction should be determined by the word "before".

Is this an intentional change or a regression? Thanks.

**Comment by plicjo** [comment]
Hey, I'm also noticing this regression in 0.9.2. I'm locked to 0.9.1 at the moment.

**Comment by amilligan** [comment]
We have also noticed this change, but in the opposite direction:

0.9.1:
```
0.business_days.since(Date.new(2017, 06, 18)) # Sunday
=> Mon, 19 Jun 2017
```

0.9.2:
```
0.business_days.since(Date.new(2017, 06, 18)) # Sunday
=> Fri, 16 Jun 2017
```

We get the same discrepancy when using `#business_hours.from_now`, on a non-business day of course.

**Comment by mlen** [comment]
Same thing for `0.business_days.after`

**Comment by bokmann** [comment]
Looking into this now.

**Comment by jaredbeck** [comment]
Can confirm: 29f611d seems to fix this issue for my use case. Will look forward to a release. Thanks, Mateusz and David.
