### ISSUE TITLE
business_time_until and business_days_until returning inconsistent results

### ISSUE THREAD

**Issue by NickHeiner** [bokmann/business_time#171]
Reading the docs, I'm not actually sure what `business_time_until` returns. I think it's seconds?

Here's my example:

```
> prev_time
=> Thu, 29 Jun 2017 01:09:26 +0000
> curr_time
=> Tue, 18 Jul 2017 18:28:55 -0400
> prev_time.business_days_until(curr_time)
=> 14
> prev_time.business_time_until(curr_time)
=> (1123201/3)
```

Assuming that `business_time_until` returns seconds, I should be able to convert to days and get a similar value to `business_days_until`. However, that did not work for me:

```
> (prev_time.business_time_until(curr_time).seconds / 60 / 60 / 24).to_i
=> 4
```

If `business_days_until` was rounding up or down for fractional days, I'd expect it to be within `+/- 1 days` of `business_time_until`. But we see here that it's `10` days off.

Am I missing something?

My system stats:

```
λ ruby -v
ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-darwin16]
λ rails -v
Rails 5.0.1

Mac OSX 10.12.5
```

**Comment by NickHeiner** [comment]
Ah, yes, I am missing something. A business day does not have `24` hours in it, it has `8`! 

This returns a value like what I'd expect:

```
> (prev_time.business_time_until(curr_time).seconds / 60 / 60 / 8).to_i
```

**Comment by sfandrew** [comment]
@bokmann  this is an awesome gem and saved me many headaches!
