### ISSUE TITLE
factory time vs. office time

### ISSUE THREAD

**Issue by philihp** [bokmann/business_time#187]
Our org operates on two different time scales; factory time and office time. Office time works 5 days a week, and has western holidays sprinkled through the year and a week or two in December. Factory time works 6 days a week, and has a different set of holidays (a month in February and a week in October).

Our main use case for using this library is to calculate timelines for product delivery, where a delivery date is calculated relative to the current date by adding a certain number of office weeks, and then a certain number of factory weeks, and then maybe another certain number of office weeks.

Would it be reasonable to submit a PR to enhance the library to accommodate this sort of thing, or would it be preferable for us to fork the repo?

**Comment by craiglittle** [comment]
Hey, @philihp.

In the past, the author of the gem has said this use case is out of scope (see: #43, #68, #118). I'm the author of a similar gem, [`biz`](https://github.com/zendesk/biz), that supports multiple schedules out of the box. Check it out; I'm happy to answer any questions you might have.

Hope that's helpful!

**Comment by bokmann** [comment]
thanks for chiming in @craiglittle.  yes, this is out of scope for this project.  An interesting problem though!
