### ISSUE TITLE
Business day calculation wrong for weekends

### ISSUE THREAD

**Issue by samror** [bokmann/business_time#192]
I am currently working in **Ruby 2.4.4** and **Rails 5.1.6**
I am calculating Business days from specific dates and I am currently facing following problem
<img width="474" alt="screen shot 2019-02-27 at 1 18 16 pm" src="https://user-images.githubusercontent.com/37530522/53475667-51970a00-3a92-11e9-803e-f1f6a574e8fb.png">
When I calculate **1 business day** from `Sunday`, the next business day is `Tuesday`, but when I calculate **1 business day** from `Today` which is `Wednesday`, it gives me `Thursday` as next busiess day. It is adding one extra day for Sunday.

**Comment by bokmann** [comment]
This is not a bug, it is operating as designed.  This has caused confusion before though; let me explain the logic.

The business day clock only ticks on business days.  Sunday is *not* a business day.  When you ask for the next business day, it rolls forward to Monday, adds one business day, and reports Tuesday.

The original use-case for this library was calculating deadlines.  If you got a task on Sunday and it was due  in "one business day", that would not be Monday, that would be Tuesday.

One way or the other, people are going to have an issue with this... it is a business requireent to interpret it this way, not a technical problem.
