### ISSUE TITLE
Support Ruby 3.0.0

### ISSUE THREAD

**Issue by tilhoft** [bokmann/business_time#199]
As it seems SortedSet will be removed from Ruby-3.0.0( as now missing from preview2)
NameError: uninitialized constant BusinessTime::Config::SortedSet
lib/business_time/config.rb:10

**Comment by spickermann** [comment]
Relevant commit: https://github.com/ruby/set/commit/dfcc8e568b

**Comment by tilhoft** [comment]
https://github.com/bokmann/business_time/pull/200
