### ISSUE TITLE
No support for different countries/contexts.

### ISSUE THREAD

**Issue by Nitrodist** [bokmann/business_time#34]
We have an app that goes into multiple states/countries/provinces and each one has a different definition of a business day. Is there a way to properly support the different contexts needed?

**Comment by craiglittle** [comment]
Hey, @Nitrodist! We just released a gem called [`biz`](https://github.com/zendesk/biz) that supports multiple schedule configurations. Check out the documentation and feel free to shoot me an email or open an issue if you have any questions.
