### ISSUE TITLE
How to deal with several business times?

### ISSUE THREAD

**Issue by zekefast** [bokmann/business_time#43]
Idea of this gem is awesome and it almost did what I need. But it seems working time configuration made almost impossible to work with several business time schedules in the same application. For example, I need to deal bank business time and call center business time. Bank usually set it's own business time, but call center has extended availability and almost no holidays ...

Is there a way to solve this issue without hard fixing the core of `business_time` gem?

**Comment by craiglittle** [comment]
Hey, @zekefast! We just released a gem called [`biz`](https://github.com/zendesk/biz) that supports multiple schedule configurations. Check out the documentation and feel free to shoot me an email or open an issue if you have any questions.
