### ISSUE TITLE
How to deal with more than one working period for a given week day?

### ISSUE THREAD

**Issue by jppeixoto** [bokmann/business_time#46]
Your gem is excelent but there is little feature that I need and I would like to know if it could be added to the gem.

I need to define working hours for a given week day without the lunch time. For instance, work hours would be from 9:00 to 12:00 and from 13:00 to 18:00. Basically I would like to configure work hours with something like this:

BusinessTime::Config.work_hours = {
  :mon=>["9:00","12:00","13:00","18:00"],
  :tue=>["9:00","12:00","13:00","18:00"],
  :wed=>["9:00","12:00","13:00","18:00"],
  :thu=>["9:00","12:00","13:00","18:00"],
  :fri=>["9:00","12:00","13:00","18:00"],
  :sat=>["10:00","15:00"]
}

**Comment by craiglittle** [comment]
Hey, @jppeixoto! We just released a gem called [`biz`](https://github.com/zendesk/biz) that supports multiple intervals per day. Check out the documentation and feel free to shoot me an email or open an issue if you have any questions.
