### ISSUE TITLE
Why was BusinessTime::Config.reset made private?

### ISSUE THREAD

**Issue by joncanady** [bokmann/business_time#81]
One of the things our app needs to do is to reload the BusinessTime configuration to calculate differences for different companies.

We've had to resort to calling `BusinessTime::Config.send(:reset)` in order to reset the configuration. I'm not sure why it's required, you'd think just over-writing the `work_hours` config setting would do the trick, but it does not. 

Here's a test script that proves the case (Ruby 1.9.3-p448, BusinessTime 0.7.2). The second `business_days.after` call should pass, but it doesn't until we call `reset`.

```ruby
require 'business_time'

business_hours = {
  mon: ['09:00', '17:00'],
  tue: ['09:00', '17:00'],
  wed: ['09:00', '17:00'],
  thu: ['09:00', '17:00'],
  fri: ['09:00', '17:00'],
}

open_24_hours = {
  mon: ['00:00', '00:00'],
  tue: ['00:00', '00:00'],
  wed: ['00:00', '00:00'],
  thu: ['00:00', '00:00'],
  fri: ['00:00', '00:00'],
  sat: ['00:00', '00:00'],
  sun: ['00:00', '00:00'],
}

# April 1, 2014 is a Tuesday
start_date = Time.parse '1 April 2014 12:00pm'

BusinessTime::Config.work_hours = open_24_hours
if 15.business_days.after(start_date) == Time.parse('16 April 2014 12:00pm')
  puts '.'
else
  puts 'F'
end

BusinessTime::Config.work_hours = business_hours
if 15.business_days.after(start_date) == Time.parse('22 April 2014 12:00pm')
  puts '.'
else
  puts 'F'
end

BusinessTime::Config.send(:reset)
BusinessTime::Config.work_hours = business_hours
if 15.business_days.after(start_date) == Time.parse('22 April 2014 12:00pm')
  puts '.'
else
  puts 'F'
end
```

**Comment by jlanatta** [comment]
Hi David,
   Is there any improvement since this last post on the multi-tennant support? If not, I'm willing to write some of the code, as long as it's within my technical skill, provided a small guidance.

Regards,
Javier

**Comment by craiglittle** [comment]
@jlanatta You might want to check out a similar gem we released recently called [`biz`](https://github.com/zendesk/biz). It supports multiple schedule configurations in the same thread.

I'm more than happy to help if you have any questions. :)

**Comment by jlanatta** [comment]
@craiglittle: thanks for the link! It covers all the functionality I need.
