### ISSUE TITLE
Basic comparison of business times

### ISSUE THREAD

**Issue by pacso** [bokmann/business_time#92]
I am trying to test a service which provides calculated deadlines for records. My test goes something like this:

```ruby
require 'rails_helper'

RSpec.describe CalculateDeadline, type: :model do
  describe 'for priority certificates' do
    let(:certificate) { create :certificate, service_level: 'priority' }

    it 'returns 3 business days' do
      expect(CalculateDeadline.call certificate).to eq 3.business_days
    end
  end
end
```

Of course, this fails miserably since there are no comparison methods provided and the two times are separate instances of `BusinessTime::BusinessDays` and as such not identical.

Can we add an equality evaluation method. If not, please explain how else I should test my code without either creating two `Time` instances to compare, or poking about in the instance with something like `3.business_days.instance_variable_get('@days')`.

**Comment by bokmann** [comment]
Just implemented this.
