### ISSUE TITLE
Business Hours per request

### ISSUE THREAD

**Issue by adpande** [bokmann/business_time#96]
Hello David,

Thanks for the great work! We are using this gem in our rails application to generate reports. 
Now some of our reports need to be calculated on 24 hrs working day and some for 8 hrs. Users generate these reports parallely. Right now the changes we are making are reflecting across the application. We were unable to change business hrs on per request basis. Is there any way to change it on per request basis? So that each of our user have different business hrs configuration? 

Thanks in advance!

Regards,
Abhishek

**Comment by craiglittle** [comment]
Hey, @adpande! I don't think `business_time` currently supports this feature, but we just released a similar gem called [`biz`](https://github.com/zendesk/biz) that supports multiple schedule configurations.

Check out the documentation and feel free to shoot me an email or open an issue if you have any questions.

**Comment by bokmann** [comment]
This has been a request several times, but multi-tenant applications are outside the scope of this gem.  The major point of this gem is to have a small dsl that simply mirrors ActiveSupport's other method calls, just adding 'business' to them, and that makes per-request configuration difficult.  I think @craiglittle's biz gem will suit you.
