### ISSUE TITLE
NoMethodError: undefined method `during_business_hours?'

### ISSUE THREAD

**Issue by thomashs-zz** [bokmann/business_time#97]
added gem 'business_time' to my rails 3.2.13 with ruby 1.9.3 project.  
I'm getting the following error:  

```
1.9.3p448 :015 > Time.now.during_business_hours?
  NoMethodError: undefined method `during_business_hours?'  for DateTime:Class
```

Any ideas?

**Comment by holden** [comment]
I have the same error but I am using Ruby 2.0:

```
Time.now.during_business_hours?
NoMethodError: undefined method `during_business_hours?' for 2015-03-05 15:42:39 +0100:Time
```

**Comment by joedaddy8** [comment]
Ditto, have the issue with Ruby 2 and Rails 4.2.0

[3] pry(#<StockValue>)> (Time.parse(@d) + 12.hours).during_business_hours?
NoMethodError: undefined method `during_business_hours?' for 2015-03-15 12:00:00 -0400:Time

**Comment by sivaraman337** [comment]
@holden once refresh/quit the server and enter to the server once again  the code will work.....
